#!/usr/bin/env bash
"""
the default server listens on port 80 for a request which is a proxy locoalhost on  port 5000
and 5001 to serve airbnb-onepage and airbnb-dynamic(ODD OR EVEN PAGE)
"""
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name 54.210.147.220;

        location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }
        location /airbnb-dynamic/number_odd_or_even/ {
        proxy_pass http://127.0.0.1:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location / {
        return 404;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root /usr/share/nginx/html;
    }
}
